PUT  http://localhost:8080/api/todos/41
Content-Type: application/json

{
    "title": "Second",
    "description": "Finish the task manager project",
    "dueDate": "2024-12-09",
    "completed": true
    
}
