Put http://localhost:8080/api/todos/17
Content-Type: application/json

{
    "title": "Complete",
    "description": "Finish the task manager project",
    "dueDate": "2024-12-09",
    "completed": false
    
}
